### PR TITLE
Resolve issue with buttons on notifications not working correctly

### LINKED ISSUE #13908: I have hit don't show again button over a dozen times and it keeps reminding me. It's clearly broken.
[WslLogs-2025-12-15_18-03-29.zip](https://github.com/user-attachments/files/24177414/WslLogs-2025-12-15_18-03-29.zip)

### Windows Version

'/c' is not recognized as an internal or external command,

### WSL Version

WSL version: 2.5.10.0 Kernel version: 6.6.87.2-1 WSLg version: 1.0.66 MSRDC version: 1.2.6074 Direct3D version: 1.611.1-81528511 DXCore version: 10.0.26100.1-240331-1435.ge-release Windows version: 10.0.26100.7462

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu Default Version: 2

### Distro Version

ubuntu

### Other Software

_No response_

### Repro Steps

Image

Make this go away when I tell it to go away. 

### Expected Behavior

I expect the don't show again button to function. 

### Actual Behavior

The don't show again button does not function I am continually reminded me this. 

### Diagnostic Logs

[WslLogs-2025-12-15_18-03-29.zip](https://github.com/user-attachments/files/24177427/WslLogs-2025-12-15_18-03-29.zip)

### PR DESCRIPTION
**Pull request by benhillis**
This pull request resolves an issue where the buttons on notifications were not working properly. This regressed with the introduction of the command line parsing helper class because this is difficult to test programmatically. There are three changes:

1. Pass arguments to wslhost.exe correctly (fix double `--` character insertion)
2. Escape `C:\Program Files\WSL\wslhost.exe` path to resolve issue with space in the path name.
3. Fix issue where the COM embedding variable was incorrectly changed from `-Embedding` to `--Embedding`
4. NFC: Push logic to read disabled notification registry key into the TelemetryWorker method.

Resolves #13908

### CODE REVIEW

File: src/windows/wslhost/main.cpp [hunk 1]
```diff
@@ -74,12 +74,10 @@ class DECLSPEC_UUID("2B9C59C3-98F1-45C8-B87B-12AE3C7927E8") NotificationActivato
         // Log telemetry when a WSL notification is activated, used to determine user engagement for notifications
         WSL_LOG_TELEMETRY("NotificationActivate", PDT_ProductAndServicePerformance, TraceLoggingValue(invokedArgs, "Arguments"));
 
-        // Prepend the executable name to the arguments so getopt can be used to parse the arguments.
-        auto commandLine = wil::GetModuleFileNameW<std::wstring>(wil::GetModuleInstanceHandle());
-        commandLine += L" ";
-        commandLine += invokedArgs;
+        // Prepend the executable name to the arguments.
+        auto commandLine = std::format(L"\"{}\" {}", wil::GetModuleFileNameW<std::wstring>(wil::GetModuleInstanceHandle()), invokedArgs);
```
Comment (OneBlue) [inline src/windows/wslhost/main.cpp]: nit: we could avoid having to do this by setting `StartIndex` to 0 when creating the `ArgumentParser`

File: src/windows/service/exe/LxssUserSession.cpp [hunk 2]
```diff
@@ -2221,9 +2222,20 @@ try
...
+                auto impersonate = wil::impersonate_token(m_userToken.get());
+                const auto lxssKey = wsl::windows::common::registry::OpenLxssUserKey();
+                drvFsNotifications = wsl::windows::common::registry::ReadDword(
+                                         lxssKey.get(), LXSS_NOTIFICATIONS_KEY, LXSS_NOTIFICATION_DRVFS_PERF_DISABLED, 0) == 0;
+            }
+
             // If a drvfs notification is requested, the first entry is the executable that triggered it.
-            LOG_IF_FAILED(wsl::windows::common::notifications::DisplayFilesystemNotification(values[0].c_str()));
-            drvFsNotifications = false;
+            if (drvFsNotifications)
```
Comment (OneBlue) [inline src/windows/service/exe/LxssUserSession.cpp]: nit: this `if` can be removed. This will also resolve the above comment

**Review by OneBlue — APPROVED** [review]
